// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ASM_Repositories.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
namespace ASM_Repositories.DBContext;

public partial class AuditManagementSystemForAviationAcademyContext : DbContext
{
    public AuditManagementSystemForAviationAcademyContext()
    {
    }

    public AuditManagementSystemForAviationAcademyContext(DbContextOptions<AuditManagementSystemForAviationAcademyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ASM_Repositories.Entities.Action> Actions { get; set; }

    public virtual DbSet<ActionStatus> ActionStatuses { get; set; }

    public virtual DbSet<Attachment> Attachments { get; set; }

    public virtual DbSet<AttachmentEntityType> AttachmentEntityTypes { get; set; }

    public virtual DbSet<Audit> Audits { get; set; }

    public virtual DbSet<AuditChecklistItem> AuditChecklistItems { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<AuditStatus> AuditStatuses { get; set; }

    public virtual DbSet<AuditTeam> AuditTeams { get; set; }

    public virtual DbSet<ChecklistItem> ChecklistItems { get; set; }

    public virtual DbSet<ChecklistTemplate> ChecklistTemplates { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Finding> Findings { get; set; }

    public virtual DbSet<FindingSeverity> FindingSeverities { get; set; }

    public virtual DbSet<FindingStatus> FindingStatuses { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<ReportRequest> ReportRequests { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RootCause> RootCauses { get; set; }

    public virtual DbSet<UserAccount> UserAccounts { get; set; }

    public virtual DbSet<VwFindingHistory> VwFindingHistories { get; set; }

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-OVUB2BP\\LUANNE;Initial Catalog=AuditManagementSystemForAviationAcademy;Persist Security Info=True;User ID=sa;Password=12345");
    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity< ASM_Repositories.Entities.Action >(entity =>
        {
            entity.HasKey(e => e.ActionId).HasName("PK__Action__FFE3F4B969F73F89");

            entity.ToTable("Action", "ams", tb => tb.HasTrigger("trg_Log_Action"));

            entity.HasIndex(e => new { e.AssignedTo, e.Status }, "IX_Action_AssignedTo_Status");

            entity.HasIndex(e => e.DueDate, "IX_Action_DueDate");

            entity.Property(e => e.ActionId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ActionID");
            entity.Property(e => e.AssignedDeptId).HasColumnName("AssignedDeptID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FindingId).HasColumnName("FindingID");
            entity.Property(e => e.ProgressPercent).HasDefaultValue((byte)0);
            entity.Property(e => e.RowVersion)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.Title).HasMaxLength(300);

            entity.HasOne(d => d.AssignedByNavigation).WithMany(p => p.ActionAssignedByNavigations)
                .HasForeignKey(d => d.AssignedBy)
                .HasConstraintName("FK__Action__Assigned__7F2BE32F");

            entity.HasOne(d => d.AssignedDept).WithMany(p => p.Actions)
                .HasForeignKey(d => d.AssignedDeptId)
                .HasConstraintName("FK__Action__Assigned__01142BA1");

            entity.HasOne(d => d.AssignedToNavigation).WithMany(p => p.ActionAssignedToNavigations)
                .HasForeignKey(d => d.AssignedTo)
                .HasConstraintName("FK__Action__Assigned__00200768");

            entity.HasOne(d => d.Finding).WithMany(p => p.Actions)
                .HasForeignKey(d => d.FindingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Action__FindingI__7E37BEF6");

            entity.HasOne(d => d.StatusNavigation).WithMany(p => p.Actions)
                .HasForeignKey(d => d.Status)
                .HasConstraintName("FK__Action__Status__02084FDA");
        });

        modelBuilder.Entity<ActionStatus>(entity =>
        {
            entity.HasKey(e => e.ActionStatus1).HasName("PK__ActionSt__7B3DC58E4712C633");

            entity.ToTable("ActionStatus", "ams");

            entity.Property(e => e.ActionStatus1)
                .HasMaxLength(50)
                .HasColumnName("ActionStatus");
        });

        modelBuilder.Entity<Attachment>(entity =>
        {
            entity.HasKey(e => e.AttachmentId).HasName("PK__Attachme__442C64DEB00D1A32");

            entity.ToTable("Attachment", "ams");

            entity.HasIndex(e => new { e.EntityType, e.EntityId }, "IX_Attachment_Entity");

            entity.Property(e => e.AttachmentId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("AttachmentID");
            entity.Property(e => e.BlobPath)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.ContentHash).HasMaxLength(32);
            entity.Property(e => e.ContentType).HasMaxLength(100);
            entity.Property(e => e.EntityId).HasColumnName("EntityID");
            entity.Property(e => e.EntityType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.UploadedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.EntityTypeNavigation).WithMany(p => p.Attachments)
                .HasForeignKey(d => d.EntityType)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Attachmen__Entit__07C12930");

            entity.HasOne(d => d.UploadedByNavigation).WithMany(p => p.Attachments)
                .HasForeignKey(d => d.UploadedBy)
                .HasConstraintName("FK__Attachmen__Uploa__08B54D69");
        });

        modelBuilder.Entity<AttachmentEntityType>(entity =>
        {
            entity.HasKey(e => e.EntityType).HasName("PK__Attachme__F21D4CA20B367E90");

            entity.ToTable("AttachmentEntityType", "ams");

            entity.Property(e => e.EntityType).HasMaxLength(50);
        });

        modelBuilder.Entity<Audit>(entity =>
        {
            entity.HasKey(e => e.AuditId).HasName("PK__Audit__A17F23B8A84C25B5");

            entity.ToTable("Audit", "ams", tb => tb.HasTrigger("trg_Log_Audit"));

            entity.Property(e => e.AuditId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("AuditID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Scope).HasMaxLength(500);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TemplateId).HasColumnName("TemplateID");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.Type).HasMaxLength(50);

            entity.HasOne(d => d.ApprovedByNavigation).WithMany(p => p.AuditApprovedByNavigations)
                .HasForeignKey(d => d.ApprovedBy)
                .HasConstraintName("FK__Audit__ApprovedB__5FB337D6");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.AuditCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__Audit__CreatedBy__5EBF139D");

            entity.HasOne(d => d.StatusNavigation).WithMany(p => p.Audits)
                .HasForeignKey(d => d.Status)
                .HasConstraintName("FK__Audit__Status__5DCAEF64");

            entity.HasOne(d => d.Template).WithMany(p => p.Audits)
                .HasForeignKey(d => d.TemplateId)
                .HasConstraintName("FK__Audit__TemplateI__5CD6CB2B");
        });

        modelBuilder.Entity<AuditChecklistItem>(entity =>
        {
            entity.HasKey(e => e.AuditItemId).HasName("PK__AuditChe__E37F18C24E61F8E1");

            entity.ToTable("AuditChecklistItem", "ams");

            entity.HasIndex(e => e.AuditId, "IX_Audit_AuditID");

            entity.Property(e => e.AuditItemId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("AuditItemID");
            entity.Property(e => e.AuditId).HasColumnName("AuditID");
            entity.Property(e => e.QuestionTextSnapshot).IsRequired();
            entity.Property(e => e.Section).HasMaxLength(200);
            entity.Property(e => e.Status).HasMaxLength(50);

            entity.HasOne(d => d.Audit).WithMany(p => p.AuditChecklistItems)
                .HasForeignKey(d => d.AuditId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AuditChec__Audit__6C190EBB");
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__AuditLog__5E5499A8DD92FB1C");

            entity.ToTable("AuditLog", "log");

            entity.HasIndex(e => e.EntityId, "IX_AuditLog_EntityID");

            entity.HasIndex(e => e.PerformedAt, "IX_AuditLog_PerformedAt").IsDescending();

            entity.Property(e => e.LogId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("LogID");
            entity.Property(e => e.Action).HasMaxLength(100);
            entity.Property(e => e.EntityId).HasColumnName("EntityID");
            entity.Property(e => e.EntityType).HasMaxLength(50);
            entity.Property(e => e.PerformedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.TableName).HasMaxLength(128);

            entity.HasOne(d => d.PerformedByNavigation).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.PerformedBy)
                .HasConstraintName("FK__AuditLog__Perfor__151B244E");
        });

        modelBuilder.Entity<AuditStatus>(entity =>
        {
            entity.HasKey(e => e.AuditStatus1).HasName("PK__AuditSta__45D7E6369D4F51B0");

            entity.ToTable("AuditStatus", "ams");

            entity.Property(e => e.AuditStatus1)
                .HasMaxLength(50)
                .HasColumnName("AuditStatus");
        });

        modelBuilder.Entity<AuditTeam>(entity =>
        {
            entity.HasKey(e => e.AuditTeamId).HasName("PK__AuditTea__7093F172898EA316");

            entity.ToTable("AuditTeam", "ams");

            entity.HasIndex(e => e.AuditId, "IX_AuditTeam_AuditID");

            entity.HasIndex(e => new { e.AuditId, e.UserId }, "UQ__AuditTea__7007AF731E5F25A8").IsUnique();

            entity.Property(e => e.AuditTeamId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("AuditTeamID");
            entity.Property(e => e.AuditId).HasColumnName("AuditID");
            entity.Property(e => e.RoleInTeam)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Audit).WithMany(p => p.AuditTeams)
                .HasForeignKey(d => d.AuditId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AuditTeam__Audit__66603565");

            entity.HasOne(d => d.User).WithMany(p => p.AuditTeams)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AuditTeam__UserI__6754599E");
        });

        modelBuilder.Entity<ChecklistItem>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PK__Checklis__727E83EBAC8657E6");

            entity.ToTable("ChecklistItem", "ams");

            entity.HasIndex(e => e.TemplateId, "IX_Checklist_Template");

            entity.Property(e => e.ItemId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ItemID");
            entity.Property(e => e.AnswerType).HasMaxLength(50);
            entity.Property(e => e.QuestionText).IsRequired();
            entity.Property(e => e.Section).HasMaxLength(200);
            entity.Property(e => e.SeverityDefault).HasMaxLength(20);
            entity.Property(e => e.TemplateId).HasColumnName("TemplateID");

            entity.HasOne(d => d.SeverityDefaultNavigation).WithMany(p => p.ChecklistItems)
                .HasForeignKey(d => d.SeverityDefault)
                .HasConstraintName("FK__Checklist__Sever__59063A47");

            entity.HasOne(d => d.Template).WithMany(p => p.ChecklistItems)
                .HasForeignKey(d => d.TemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Checklist__Templ__571DF1D5");
        });

        modelBuilder.Entity<ChecklistTemplate>(entity =>
        {
            entity.HasKey(e => e.TemplateId).HasName("PK__Checklis__F87ADD07BFF290DB");

            entity.ToTable("ChecklistTemplate", "ams");

            entity.Property(e => e.TemplateId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("TemplateID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Version).HasMaxLength(50);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.ChecklistTemplates)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__Checklist__Creat__5165187F");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.DeptId).HasName("PK__Departme__0148818E12B2BECB");

            entity.ToTable("Department", "ams");

            entity.Property(e => e.DeptId).HasColumnName("DeptID");
            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<Finding>(entity =>
        {
            entity.HasKey(e => e.FindingId).HasName("PK__Finding__19D671C22DCDC03A");

            entity.ToTable("Finding", "ams", tb => tb.HasTrigger("trg_Log_Finding"));

            entity.HasIndex(e => new { e.AuditId, e.Status }, "IX_Finding_AuditID_Status");

            entity.HasIndex(e => new { e.DeptId, e.Severity }, "IX_Finding_DeptID_Severity");

            entity.Property(e => e.FindingId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("FindingID");
            entity.Property(e => e.AuditId).HasColumnName("AuditID");
            entity.Property(e => e.AuditItemId).HasColumnName("AuditItemID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DeptId).HasColumnName("DeptID");
            entity.Property(e => e.ExternalAuditorName).HasMaxLength(200);
            entity.Property(e => e.ReviewerId).HasColumnName("ReviewerID");
            entity.Property(e => e.RootCauseId).HasColumnName("RootCauseID");
            entity.Property(e => e.RowVersion)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.Severity).HasMaxLength(20);
            entity.Property(e => e.Source).HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Open");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(300);

            entity.HasOne(d => d.Audit).WithMany(p => p.Findings)
                .HasForeignKey(d => d.AuditId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Finding__AuditID__71D1E811");

            entity.HasOne(d => d.AuditItem).WithMany(p => p.Findings)
                .HasForeignKey(d => d.AuditItemId)
                .HasConstraintName("FK__Finding__AuditIt__72C60C4A");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.FindingCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__Finding__Created__76969D2E");

            entity.HasOne(d => d.Dept).WithMany(p => p.Findings)
                .HasForeignKey(d => d.DeptId)
                .HasConstraintName("FK__Finding__DeptID__75A278F5");

            entity.HasOne(d => d.Reviewer).WithMany(p => p.FindingReviewers)
                .HasForeignKey(d => d.ReviewerId)
                .HasConstraintName("FK__Finding__Reviewe__7A672E12");

            entity.HasOne(d => d.RootCause).WithMany(p => p.Findings)
                .HasForeignKey(d => d.RootCauseId)
                .HasConstraintName("FK__Finding__RootCau__74AE54BC");

            entity.HasOne(d => d.SeverityNavigation).WithMany(p => p.Findings)
                .HasForeignKey(d => d.Severity)
                .HasConstraintName("FK__Finding__Severit__73BA3083");

            entity.HasOne(d => d.StatusNavigation).WithMany(p => p.Findings)
                .HasForeignKey(d => d.Status)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Finding__Status__797309D9");
        });

        modelBuilder.Entity<FindingSeverity>(entity =>
        {
            entity.HasKey(e => e.Severity).HasName("PK__FindingS__96F5CD15C02AA915");

            entity.ToTable("FindingSeverity", "ams");

            entity.Property(e => e.Severity).HasMaxLength(20);
        });

        modelBuilder.Entity<FindingStatus>(entity =>
        {
            entity.HasKey(e => e.FindingStatus1).HasName("PK__FindingS__B9A531DF5E4F114E");

            entity.ToTable("FindingStatus", "ams");

            entity.Property(e => e.FindingStatus1)
                .HasMaxLength(50)
                .HasColumnName("FindingStatus");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E327A4D606D");

            entity.ToTable("Notification", "ams");

            entity.Property(e => e.NotificationId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("NotificationID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.EntityId).HasColumnName("EntityID");
            entity.Property(e => e.EntityType).HasMaxLength(50);
            entity.Property(e => e.Title).HasMaxLength(200);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.EntityTypeNavigation).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.EntityType)
                .HasConstraintName("FK__Notificat__Entit__0F624AF8");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Notificat__UserI__0E6E26BF");
        });

        modelBuilder.Entity<ReportRequest>(entity =>
        {
            entity.HasKey(e => e.ReportRequestId).HasName("PK__ReportRe__1609F931C68D52FD");

            entity.ToTable("ReportRequest", "ams");

            entity.Property(e => e.ReportRequestId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ReportRequestID");
            entity.Property(e => e.FilePath).HasMaxLength(1000);
            entity.Property(e => e.RequestedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Status).HasMaxLength(50);

            entity.HasOne(d => d.RequestedByNavigation).WithMany(p => p.ReportRequests)
                .HasForeignKey(d => d.RequestedBy)
                .HasConstraintName("FK__ReportReq__Reque__19DFD96B");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleName).HasName("PK__Role__8A2B616187FE0763");

            entity.ToTable("Role", "ams");

            entity.Property(e => e.RoleName).HasMaxLength(50);
            entity.Property(e => e.Description).HasMaxLength(250);
        });

        modelBuilder.Entity<RootCause>(entity =>
        {
            entity.HasKey(e => e.RootCauseId).HasName("PK__RootCaus__EAE5E40E2FAE18E7");

            entity.ToTable("RootCause", "ams");

            entity.Property(e => e.RootCauseId).HasColumnName("RootCauseID");
            entity.Property(e => e.Category).HasMaxLength(100);
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<UserAccount>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__UserAcco__1788CCAC24440160");

            entity.ToTable("UserAccount", "auth", tb => tb.HasTrigger("trg_UserAccount_Delete"));

            entity.HasIndex(e => new { e.DeptId, e.RoleName }, "IX_User_Dept_Role");

            entity.HasIndex(e => e.Email, "UQ__UserAcco__A9D105346D1562FC").IsUnique();

            entity.Property(e => e.UserId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("UserID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DeptId).HasColumnName("DeptID");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordHash).HasMaxLength(64);
            entity.Property(e => e.PasswordSalt).HasMaxLength(32);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RowVersion)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.HasOne(d => d.Dept).WithMany(p => p.UserAccounts)
                .HasForeignKey(d => d.DeptId)
                .HasConstraintName("FK__UserAccou__DeptI__48CFD27E");

            entity.HasOne(d => d.RoleNameNavigation).WithMany(p => p.UserAccounts)
                .HasForeignKey(d => d.RoleName)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserAccou__RoleN__47DBAE45");
        });

        modelBuilder.Entity<VwFindingHistory>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_FindingHistory", "ams");

            entity.Property(e => e.Action).HasMaxLength(100);
            entity.Property(e => e.FindingId).HasColumnName("FindingID");
            entity.Property(e => e.PerformedBy).HasMaxLength(200);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}