// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AccessGrant
{
    public Guid GrantId { get; set; }

    public Guid AuditId { get; set; }

    public Guid AuditorId { get; set; }

    public int DeptId { get; set; }

    public DateTime ValidFrom { get; set; }

    public DateTime ValidTo { get; set; }

    public string VerifyCode { get; set; }

    public int TtlMinutes { get; set; }

    public string QrToken { get; set; }

    public string QrUrl { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Audit Audit { get; set; }

    public virtual UserAccount Auditor { get; set; }

    public virtual Department Dept { get; set; }
}

