// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class Action
{
    public Guid ActionId { get; set; }

    public Guid FindingId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public Guid? AssignedBy { get; set; }

    public Guid? AssignedTo { get; set; }

    public int? AssignedDeptId { get; set; }

    public string Status { get; set; }

    public byte? ProgressPercent { get; set; }

    public DateTime? DueDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ClosedAt { get; set; }

    public string ReviewFeedback { get; set; }

    public virtual UserAccount AssignedByNavigation { get; set; }

    public virtual Department AssignedDept { get; set; }

    public virtual UserAccount AssignedToNavigation { get; set; }

    public virtual Finding Finding { get; set; }

    public virtual ActionStatus StatusNavigation { get; set; }
}