// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class ActionStatus
{
    public string ActionStatus1 { get; set; }

    public virtual ICollection<Action> Actions { get; set; } = new List<Action>();
}