// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AttachmentEntityType
{
    public string EntityType { get; set; }

    public virtual ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}