// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class Attachment
{
    public Guid AttachmentId { get; set; }

    public string EntityType { get; set; }

    public Guid EntityId { get; set; }

    public string FileName { get; set; }

    public string BlobPath { get; set; }

    public string ContentType { get; set; }

    public long? SizeBytes { get; set; }

    public Guid? UploadedBy { get; set; }

    public DateTime UploadedAt { get; set; }

    public byte[] ContentHash { get; set; }

    public DateOnly? RetentionUntil { get; set; }

    public bool IsArchived { get; set; }

    public virtual AttachmentEntityType EntityTypeNavigation { get; set; }

    public virtual UserAccount UploadedByNavigation { get; set; }
}