// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditAssignment
{
    public Guid AssignmentId { get; set; }

    public Guid AuditId { get; set; }

    public int DeptId { get; set; }

    public Guid AuditorId { get; set; }

    public string Notes { get; set; }

    public DateTime AssignedAt { get; set; }

    public string Status { get; set; }

    public virtual Audit Audit { get; set; }

    public virtual UserAccount Auditor { get; set; }

    public virtual Department Dept { get; set; }
}