// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditChecklistItem
{
    public Guid AuditItemId { get; set; }

    public Guid AuditId { get; set; }

    public string QuestionTextSnapshot { get; set; }

    public string Section { get; set; }

    public int? Order { get; set; }

    public string Status { get; set; }

    public string Comment { get; set; }

    public virtual Audit Audit { get; set; }

    public virtual ICollection<ChecklistItemNoFinding> ChecklistItemNoFindings { get; set; } = new List<ChecklistItemNoFinding>();

    public virtual ICollection<Finding> Findings { get; set; } = new List<Finding>();
}