// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditLog
{
    public Guid LogId { get; set; }

    public string EntityType { get; set; }

    public Guid? EntityId { get; set; }

    public string Action { get; set; }

    public Guid? PerformedBy { get; set; }

    public DateTime PerformedAt { get; set; }

    public string Data { get; set; }

    public virtual UserAccount PerformedByNavigation { get; set; }
}