// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class Audit
{
    public Guid AuditId { get; set; }

    public string Title { get; set; }

    public string Type { get; set; }

    public string Scope { get; set; }

    public Guid? TemplateId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Status { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsPublished { get; set; }

    public string Objective { get; set; }

    public virtual ICollection<AuditApproval> AuditApprovals { get; set; } = new List<AuditApproval>();

    public virtual ICollection<AuditChecklistItem> AuditChecklistItems { get; set; } = new List<AuditChecklistItem>();

    public virtual ICollection<AuditCriteriaMap> AuditCriteriaMaps { get; set; } = new List<AuditCriteriaMap>();

    public virtual ICollection<AuditDocument> AuditDocuments { get; set; } = new List<AuditDocument>();

    public virtual ICollection<AuditScopeDepartment> AuditScopeDepartments { get; set; } = new List<AuditScopeDepartment>();

    public virtual ICollection<AuditTeam> AuditTeams { get; set; } = new List<AuditTeam>();

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual ICollection<Finding> Findings { get; set; } = new List<Finding>();

    public virtual AuditStatus StatusNavigation { get; set; }

    public virtual ChecklistTemplate Template { get; set; }
}