// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditSchedule
{
    public Guid ScheduleId { get; set; }

    public Guid AuditId { get; set; }

    public string MilestoneName { get; set; }

    public DateTime DueDate { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public virtual Audit Audit { get; set; }
}