// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditScopeDepartment
{
    public Guid AuditScopeId { get; set; }

    public Guid AuditId { get; set; }

    public string Status { get; set; }

    public int DeptId { get; set; }

    public bool? SensitiveFlag { get; set; }

    public string Areas { get; set; }

    public string Notes { get; set; }

    public virtual Audit Audit { get; set; }

    public virtual Department Dept { get; set; }
}