// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditPlanAssignment
{
    public int AssignmentId { get; set; }

    public int AuditorId { get; set; }

    public int AssignBy { get; set; }

    public DateTime AssignedDate { get; set; }

    public string Status { get; set; }

    public string Remarks { get; set; }
}