// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditCriteriaMap
{
    public Guid AuditId { get; set; }

    public Guid CriteriaId { get; set; }

    public string Status { get; set; }

    public virtual Audit Audit { get; set; }

    public virtual AuditCriterion Criteria { get; set; }
}