// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditTeam
{
    public Guid AuditTeamId { get; set; }

    public Guid AuditId { get; set; }

    public Guid UserId { get; set; }

    public string RoleInTeam { get; set; }

    public bool IsLead { get; set; }

    public virtual Audit Audit { get; set; }

    public virtual UserAccount User { get; set; }
}