// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditDocument
{
    public Guid DocId { get; set; }

    public Guid AuditId { get; set; }

    public string DocumentType { get; set; }

    public string Title { get; set; }

    public string BlobPath { get; set; }

    public string ContentType { get; set; }

    public long? SizeBytes { get; set; }

    public Guid? UploadedBy { get; set; }

    public DateTime UploadedAt { get; set; }

    public bool IsFinalVersion { get; set; }

    public string Status { get; set; }

    public virtual Audit Audit { get; set; }

    public virtual UserAccount UploadedByNavigation { get; set; }
}