// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditStatus
{
    public string AuditStatus1 { get; set; }

    public virtual ICollection<Audit> Audits { get; set; } = new List<Audit>();
}