// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditApproval
{
    public Guid AuditApprovalId { get; set; }

    public Guid AuditId { get; set; }

    public Guid ApproverId { get; set; }

    public string ApprovalLevel { get; set; }

    public string Status { get; set; }

    public string Comment { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual UserAccount Approver { get; set; }

    public virtual Audit Audit { get; set; }
}