// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditChecklistTemplateMap
{
    public Guid AuditId { get; set; }

    public Guid TemplateId { get; set; }

    public DateTime AssignedAt { get; set; }

    public Guid? AssignedBy { get; set; }

    public string Status { get; set; }

    public virtual UserAccount AssignedByNavigation { get; set; }

    public virtual Audit Audit { get; set; }

    public virtual ChecklistTemplate Template { get; set; }
}