// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditCriterion
{
    public Guid CriteriaId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ReferenceCode { get; set; }

    public string PublishedBy { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<AuditCriteriaMap> AuditCriteriaMaps { get; set; } = new List<AuditCriteriaMap>();
}