// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class AuditPlanAssignment
{
    public Guid AssignmentId { get; set; }

    public Guid AuditorId { get; set; }

    public Guid AssignBy { get; set; }

    public DateTime AssignedDate { get; set; }

    public string Status { get; set; }

    public string Remarks { get; set; }

    public virtual UserAccount AssignByNavigation { get; set; }

    public virtual UserAccount Auditor { get; set; }
}