// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class ChecklistItemNoFinding
{
public int Id { get; set; }

<<<<<<< HEAD
    public string Title { get; set; }
=======
public int AuditChecklistItemId { get; set; }

public string Title { get; set; }
>>>>>>> 965180f0f7181045f6ecb0e6032019ca4d5c1838

public string Reason { get; set; }

public DateOnly? DateOfCompliance { get; set; }

public TimeOnly? TimeOfCompliance { get; set; }

public string Department { get; set; }

<<<<<<< HEAD
    public DateTime CreatedDate { get; set; }
=======
public int CreatedBy { get; set; }

public DateTime CreatedDate { get; set; }
>>>>>>> 965180f0f7181045f6ecb0e6032019ca4d5c1838

public Guid WitnessId { get; set; }

<<<<<<< HEAD
    public Guid CreatedBy { get; set; }

    public Guid AuditChecklistItemId { get; set; }

    public virtual AuditChecklistItem AuditChecklistItem { get; set; }

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual UserAccount Witness { get; set; }
}
=======
public virtual UserAccount Witness { get; set; }
}
>>>>>>> 965180f0f7181045f6ecb0e6032019ca4d5c1838
