// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class ChecklistTemplate
{
    public Guid TemplateId { get; set; }

    public string Name { get; set; }

    public string Version { get; set; }

    public string Description { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public bool IsActive { get; set; }

    public int? DeptId { get; set; }

    public virtual ICollection<AuditChecklistTemplateMap> AuditChecklistTemplateMaps { get; set; } = new List<AuditChecklistTemplateMap>();

    public virtual ICollection<Audit> Audits { get; set; } = new List<Audit>();

    public virtual ICollection<ChecklistItem> ChecklistItems { get; set; } = new List<ChecklistItem>();

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual Department Dept { get; set; }
}