// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class ChecklistItem
{
    public Guid ItemId { get; set; }

    public Guid TemplateId { get; set; }

    public string Section { get; set; }

    public int Order { get; set; }

    public string QuestionText { get; set; }

    public string AnswerType { get; set; }

    public string Status { get; set; }

    public string SeverityDefault { get; set; }

    public virtual FindingSeverity SeverityDefaultNavigation { get; set; }

    public virtual ChecklistTemplate Template { get; set; }
}