// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class ChecklistItemNoFinding
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Reason { get; set; }

    public DateOnly? DateOfCompliance { get; set; }

    public TimeOnly? TimeOfCompliance { get; set; }

    public string Department { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid WitnessId { get; set; }

    public Guid CreatedBy { get; set; }

    public Guid AuditChecklistItemId { get; set; }

    public virtual AuditChecklistItem AuditChecklistItem { get; set; }

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual UserAccount Witness { get; set; }
}