// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class DepartmentSensitiveArea
{
    public Guid Id { get; set; }

    public int DeptId { get; set; }

    public string SensitiveAreas { get; set; } // JSON array: ["Area1", "Area2"]

    public string DefaultNotes { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public virtual Department Dept { get; set; }
}

