// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class DepartmentHead
{
    public Guid DeptHeadId { get; set; }

    public int DeptId { get; set; }

    public Guid UserId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Status { get; set; }

    public virtual Department Dept { get; set; }

    public virtual UserAccount User { get; set; }
}