// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class Finding
{
    public Guid FindingId { get; set; }

    public Guid AuditId { get; set; }

    public Guid? AuditItemId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Severity { get; set; }

    public int? RootCauseId { get; set; }

    public int? DeptId { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public DateTime? Deadline { get; set; }

    public Guid? ReviewerId { get; set; }

    public string Source { get; set; }

    public string ExternalAuditorName { get; set; }

    public int? WitnessId { get; set; }

    public string FindingType { get; set; }

    public DateTime? ClosedAt { get; set; }

    public virtual ICollection<Action> Actions { get; set; } = new List<Action>();

    public virtual Audit Audit { get; set; }

    public virtual AuditChecklistItem AuditItem { get; set; }

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual Department Dept { get; set; }

    public virtual UserAccount Reviewer { get; set; }

    public virtual RootCause RootCause { get; set; }

    public virtual FindingSeverity SeverityNavigation { get; set; }

    public virtual FindingStatus StatusNavigation { get; set; }
}