// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class ReportRequest
{
    public Guid ReportRequestId { get; set; }

    public Guid? RequestedBy { get; set; }

    public string Parameters { get; set; }

    public string Status { get; set; }

    public string FilePath { get; set; }

    public DateTime RequestedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual UserAccount RequestedByNavigation { get; set; }
}