// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class SensitiveAreaLevel
{
    public string Level { get; set; }

    public virtual ICollection<DepartmentSensitiveArea> DepartmentSensitiveAreas { get; set; } = new List<DepartmentSensitiveArea>();
}

