// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class UserAccount
{
    public Guid UserId { get; set; }

    public string Email { get; set; }

    public string FullName { get; set; }

    public string RoleName { get; set; }

    public int? DeptId { get; set; }

    public byte[] PasswordHash { get; set; }

    public byte[] PasswordSalt { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? LastLogin { get; set; }

    public int FailedLoginCount { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Action> ActionAssignedByNavigations { get; set; } = new List<Action>();

    public virtual ICollection<Action> ActionAssignedToNavigations { get; set; } = new List<Action>();

    public virtual ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();

    public virtual ICollection<AuditApproval> AuditApprovals { get; set; } = new List<AuditApproval>();

    public virtual ICollection<AuditAssignment> AuditAssignments { get; set; } = new List<AuditAssignment>();

    public virtual ICollection<AuditChecklistTemplateMap> AuditChecklistTemplateMaps { get; set; } = new List<AuditChecklistTemplateMap>();

    public virtual ICollection<AuditDocument> AuditDocuments { get; set; } = new List<AuditDocument>();

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<AuditTeam> AuditTeams { get; set; } = new List<AuditTeam>();

    public virtual ICollection<Audit> Audits { get; set; } = new List<Audit>();

    public virtual ICollection<ChecklistTemplate> ChecklistTemplates { get; set; } = new List<ChecklistTemplate>();

    public virtual ICollection<DepartmentHead> DepartmentHeads { get; set; } = new List<DepartmentHead>();

    public virtual Department Dept { get; set; }

    public virtual ICollection<Finding> FindingCreatedByNavigations { get; set; } = new List<Finding>();

    public virtual ICollection<Finding> FindingReviewers { get; set; } = new List<Finding>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<ReportRequest> ReportRequests { get; set; } = new List<ReportRequest>();

    public virtual Role RoleNameNavigation { get; set; }
}