// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASM_Repositories.Entities;

public partial class VwFindingHistory
{
    public Guid? FindingId { get; set; }

    public string Action { get; set; }

    public DateTime PerformedAt { get; set; }

    public string PerformedBy { get; set; }

    public string OldData { get; set; }

    public string NewData { get; set; }
}