// <auto-generated />
using System;
using ASM_Repositories.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM_Repositories.Migrations
{
    [DbContext(typeof(AuditManagementSystemForAviationAcademyContext))]
    [Migration("20251108064329_Update_auditlogFields")]
    partial class Update_auditlogFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASM_Repositories.Entities.Action", b =>
                {
                    b.Property<Guid>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ActionID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AssignedDeptId")
                        .HasColumnType("int")
                        .HasColumnName("AssignedDeptID");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FindingID");

                    b.Property<byte?>("ProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("ReviewFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ActionId")
                        .HasName("PK__Action__FFE3F4B9A4603102");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("AssignedDeptId");

                    b.HasIndex("FindingId");

                    b.HasIndex("Status");

                    b.HasIndex(new[] { "AssignedTo", "Status" }, "IX_Action_AssignedTo_Status");

                    b.HasIndex(new[] { "DueDate" }, "IX_Action_DueDate");

                    b.ToTable("Action", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ActionStatus", b =>
                {
                    b.Property<string>("ActionStatus1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ActionStatus");

                    b.HasKey("ActionStatus1")
                        .HasName("PK__ActionSt__7B3DC58E4DAFA866");

                    b.ToTable("ActionStatus", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Attachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AttachmentID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("ContentHash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("RetentionUntil")
                        .HasColumnType("date");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AttachmentId")
                        .HasName("PK__Attachme__442C64DE512B798F");

                    b.HasIndex("UploadedBy");

                    b.HasIndex(new[] { "EntityType", "EntityId" }, "IX_Attachment_Entity");

                    b.ToTable("Attachment", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AttachmentEntityType", b =>
                {
                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EntityType")
                        .HasName("PK__Attachme__F21D4CA2580E4F9D");

                    b.ToTable("AttachmentEntityType", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Audit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Objective")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Scope")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TemplateID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditId")
                        .HasName("PK__Audit__A17F23B854AA04E5");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Status");

                    b.HasIndex("TemplateId");

                    b.ToTable("Audit", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditApproval", b =>
                {
                    b.Property<Guid>("AuditApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditApprovalID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ApprovalLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApproverID");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditApprovalId")
                        .HasName("PK__AuditApp__1C6F87158FA8BD28");

                    b.HasIndex("ApproverId");

                    b.HasIndex(new[] { "AuditId" }, "IX_AuditApproval_AuditID");

                    b.HasIndex(new[] { "AuditId", "ApproverId", "ApprovalLevel" }, "UQ__AuditApp__592EA2A7168E30A8")
                        .IsUnique();

                    b.ToTable("AuditApproval", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditChecklistItem", b =>
                {
                    b.Property<Guid>("AuditItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditItemID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("QuestionTextSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditItemId")
                        .HasName("PK__AuditChe__E37F18C217B7CDF3");

                    b.HasIndex(new[] { "AuditId" }, "IX_Audit_AuditID");

                    b.ToTable("AuditChecklistItem", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditCriteriaMap", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID");

                    b.Property<Guid>("CriteriaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CriteriaID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditId", "CriteriaId")
                        .HasName("PK__Audit_Cr__6E998E0ABFC90124");

                    b.HasIndex("CriteriaId");

                    b.ToTable("Audit_Criteria_Map", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditCriterion", b =>
                {
                    b.Property<Guid>("CriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CriteriaID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CriteriaId")
                        .HasName("PK__AuditCri__FE6ADB2D1E0300D4");

                    b.ToTable("AuditCriteria", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditDocument", b =>
                {
                    b.Property<Guid>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsFinalVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocId")
                        .HasName("PK__AuditDoc__3EF1888DB890BF0C");

                    b.HasIndex("UploadedBy");

                    b.HasIndex(new[] { "AuditId" }, "IX_AuditDocument_AuditID");

                    b.ToTable("AuditDocument", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LogID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LogId")
                        .HasName("PK__AuditLog__5E5499A86BF1FE20");

                    b.HasIndex("PerformedBy");

                    b.ToTable("AuditLog", "log");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditScopeDepartment", b =>
                {
                    b.Property<Guid>("AuditScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditScopeID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditScopeId")
                        .HasName("PK__AuditSco__405679D3D34BF00B");

                    b.HasIndex("AuditId");

                    b.HasIndex("DeptId");

                    b.ToTable("AuditScopeDepartment", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditStatus", b =>
                {
                    b.Property<string>("AuditStatus1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AuditStatus");

                    b.HasKey("AuditStatus1")
                        .HasName("PK__AuditSta__45D7E636730CC5AF");

                    b.ToTable("AuditStatus", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditTeam", b =>
                {
                    b.Property<Guid>("AuditTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditTeamID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID");

                    b.Property<bool>("IsLead")
                        .HasColumnType("bit");

                    b.Property<string>("RoleInTeam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("AuditTeamId")
                        .HasName("PK__AuditTea__7093F172AF8F2CEE");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AuditId" }, "IX_AuditTeam_AuditID");

                    b.HasIndex(new[] { "AuditId", "UserId" }, "UQ__AuditTea__7007AF73218720A0")
                        .IsUnique();

                    b.ToTable("AuditTeam", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ChecklistItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ItemID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AnswerType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeverityDefault")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TemplateID");

                    b.HasKey("ItemId")
                        .HasName("PK__Checklis__727E83EB0D9B4F88");

                    b.HasIndex("SeverityDefault");

                    b.HasIndex(new[] { "TemplateId" }, "IX_Checklist_Template");

                    b.ToTable("ChecklistItem", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ChecklistTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TemplateID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TemplateId")
                        .HasName("PK__Checklis__F87ADD07572BA702");

                    b.HasIndex("CreatedBy");

                    b.ToTable("ChecklistTemplate", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeptId")
                        .HasName("PK__Departme__0148818E083A3CEC");

                    b.ToTable("Department", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.DepartmentHead", b =>
                {
                    b.Property<Guid>("DeptHeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeptHeadID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("DeptHeadId")
                        .HasName("PK__Departme__04A193417906A8B4");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "DeptId" }, "IX_DeptHead_DeptID");

                    b.HasIndex(new[] { "DeptId", "UserId" }, "UQ__Departme__D0300D454B9884C0")
                        .IsUnique();

                    b.ToTable("DepartmentHead", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Finding", b =>
                {
                    b.Property<Guid>("FindingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FindingID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID");

                    b.Property<Guid?>("AuditItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditItemID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalAuditorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReviewerID");

                    b.Property<int?>("RootCauseId")
                        .HasColumnType("int")
                        .HasColumnName("RootCauseID");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("FindingId")
                        .HasName("PK__Finding__19D671C271F1A8F1");

                    b.HasIndex("AuditItemId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("RootCauseId");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex(new[] { "AuditId", "Status" }, "IX_Finding_AuditID_Status");

                    b.HasIndex(new[] { "DeptId", "Severity" }, "IX_Finding_DeptID_Severity");

                    b.ToTable("Finding", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.FindingSeverity", b =>
                {
                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Severity")
                        .HasName("PK__FindingS__96F5CD159FC0754C");

                    b.ToTable("FindingSeverity", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.FindingStatus", b =>
                {
                    b.Property<string>("FindingStatus1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FindingStatus");

                    b.HasKey("FindingStatus1")
                        .HasName("PK__FindingS__B9A531DFE9BD16DD");

                    b.ToTable("FindingStatus", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NotificationID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E32DACF1590");

                    b.HasIndex("EntityType");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ReportRequest", b =>
                {
                    b.Property<Guid>("ReportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReportRequestID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("RequestedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportRequestId")
                        .HasName("PK__ReportRe__1609F931CB3E84AE");

                    b.HasIndex("RequestedBy");

                    b.ToTable("ReportRequest", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Role", b =>
                {
                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("RoleName")
                        .HasName("PK__Role__8A2B6161E48C8F2C");

                    b.ToTable("Role", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.RootCause", b =>
                {
                    b.Property<int>("RootCauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RootCauseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RootCauseId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RootCauseId")
                        .HasName("PK__RootCaus__EAE5E40EC3D9468A");

                    b.ToTable("RootCause", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__UserAcco__1788CCAC78E72EFF");

                    b.HasIndex("RoleName");

                    b.HasIndex(new[] { "DeptId", "RoleName" }, "IX_User_Dept_Role");

                    b.HasIndex(new[] { "Email" }, "UQ__UserAcco__A9D10534D42B0AFC")
                        .IsUnique();

                    b.ToTable("UserAccount", "auth");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Action", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.UserAccount", "AssignedByNavigation")
                        .WithMany("ActionAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .HasConstraintName("FK__Action__Assigned__09A971A2");

                    b.HasOne("ASM_Repositories.Entities.Department", "AssignedDept")
                        .WithMany("Actions")
                        .HasForeignKey("AssignedDeptId")
                        .HasConstraintName("FK__Action__Assigned__0B91BA14");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "AssignedToNavigation")
                        .WithMany("ActionAssignedToNavigations")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK__Action__Assigned__0A9D95DB");

                    b.HasOne("ASM_Repositories.Entities.Finding", "Finding")
                        .WithMany("Actions")
                        .HasForeignKey("FindingId")
                        .IsRequired()
                        .HasConstraintName("FK__Action__FindingI__08B54D69");

                    b.HasOne("ASM_Repositories.Entities.ActionStatus", "StatusNavigation")
                        .WithMany("Actions")
                        .HasForeignKey("Status")
                        .HasConstraintName("FK__Action__Status__0C85DE4D");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("AssignedDept");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("Finding");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Attachment", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.AttachmentEntityType", "EntityTypeNavigation")
                        .WithMany("Attachments")
                        .HasForeignKey("EntityType")
                        .IsRequired()
                        .HasConstraintName("FK__Attachmen__Entit__123EB7A3");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "UploadedByNavigation")
                        .WithMany("Attachments")
                        .HasForeignKey("UploadedBy")
                        .HasConstraintName("FK__Attachmen__Uploa__1332DBDC");

                    b.Navigation("EntityTypeNavigation");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Audit", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.UserAccount", "CreatedByNavigation")
                        .WithMany("Audits")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Audit__CreatedBy__6383C8BA");

                    b.HasOne("ASM_Repositories.Entities.AuditStatus", "StatusNavigation")
                        .WithMany("Audits")
                        .HasForeignKey("Status")
                        .HasConstraintName("FK__Audit__Status__628FA481");

                    b.HasOne("ASM_Repositories.Entities.ChecklistTemplate", "Template")
                        .WithMany("Audits")
                        .HasForeignKey("TemplateId")
                        .HasConstraintName("FK__Audit__TemplateI__619B8048");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("StatusNavigation");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditApproval", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.UserAccount", "Approver")
                        .WithMany("AuditApprovals")
                        .HasForeignKey("ApproverId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditAppr__Appro__71D1E811");

                    b.HasOne("ASM_Repositories.Entities.Audit", "Audit")
                        .WithMany("AuditApprovals")
                        .HasForeignKey("AuditId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditAppr__Audit__70DDC3D8");

                    b.Navigation("Approver");

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditChecklistItem", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Audit", "Audit")
                        .WithMany("AuditChecklistItems")
                        .HasForeignKey("AuditId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditChec__Audit__76969D2E");

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditCriteriaMap", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Audit", "Audit")
                        .WithMany("AuditCriteriaMaps")
                        .HasForeignKey("AuditId")
                        .IsRequired()
                        .HasConstraintName("FK__Audit_Cri__Audit__37703C52");

                    b.HasOne("ASM_Repositories.Entities.AuditCriterion", "Criteria")
                        .WithMany("AuditCriteriaMaps")
                        .HasForeignKey("CriteriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Audit_Cri__Crite__3864608B");

                    b.Navigation("Audit");

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditDocument", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Audit", "Audit")
                        .WithMany("AuditDocuments")
                        .HasForeignKey("AuditId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditDocu__Audit__18EBB532");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "UploadedByNavigation")
                        .WithMany("AuditDocuments")
                        .HasForeignKey("UploadedBy")
                        .HasConstraintName("FK__AuditDocu__Uploa__19DFD96B");

                    b.Navigation("Audit");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditLog", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.UserAccount", "PerformedByNavigation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedBy")
                        .HasConstraintName("FK__AuditLog__Perfor__2645B050");

                    b.Navigation("PerformedByNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditScopeDepartment", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Audit", "Audit")
                        .WithMany("AuditScopeDepartments")
                        .HasForeignKey("AuditId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditScop__Audit__2FCF1A8A");

                    b.HasOne("ASM_Repositories.Entities.Department", "Dept")
                        .WithMany("AuditScopeDepartments")
                        .HasForeignKey("DeptId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditScop__DeptI__30C33EC3");

                    b.Navigation("Audit");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditTeam", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Audit", "Audit")
                        .WithMany("AuditTeams")
                        .HasForeignKey("AuditId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditTeam__Audit__6A30C649");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "User")
                        .WithMany("AuditTeams")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditTeam__UserI__6B24EA82");

                    b.Navigation("Audit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ChecklistItem", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.FindingSeverity", "SeverityDefaultNavigation")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("SeverityDefault")
                        .HasConstraintName("FK__Checklist__Sever__5DCAEF64");

                    b.HasOne("ASM_Repositories.Entities.ChecklistTemplate", "Template")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("FK__Checklist__Templ__5BE2A6F2");

                    b.Navigation("SeverityDefaultNavigation");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ChecklistTemplate", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.UserAccount", "CreatedByNavigation")
                        .WithMany("ChecklistTemplates")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Checklist__Creat__5629CD9C");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.DepartmentHead", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Department", "Dept")
                        .WithMany("DepartmentHeads")
                        .HasForeignKey("DeptId")
                        .IsRequired()
                        .HasConstraintName("FK__Departmen__DeptI__5070F446");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "User")
                        .WithMany("DepartmentHeads")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Departmen__UserI__5165187F");

                    b.Navigation("Dept");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Finding", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Audit", "Audit")
                        .WithMany("Findings")
                        .HasForeignKey("AuditId")
                        .IsRequired()
                        .HasConstraintName("FK__Finding__AuditID__7C4F7684");

                    b.HasOne("ASM_Repositories.Entities.AuditChecklistItem", "AuditItem")
                        .WithMany("Findings")
                        .HasForeignKey("AuditItemId")
                        .HasConstraintName("FK__Finding__AuditIt__7D439ABD");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "CreatedByNavigation")
                        .WithMany("FindingCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Finding__Created__01142BA1");

                    b.HasOne("ASM_Repositories.Entities.Department", "Dept")
                        .WithMany("Findings")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK__Finding__DeptID__00200768");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "Reviewer")
                        .WithMany("FindingReviewers")
                        .HasForeignKey("ReviewerId")
                        .HasConstraintName("FK__Finding__Reviewe__04E4BC85");

                    b.HasOne("ASM_Repositories.Entities.RootCause", "RootCause")
                        .WithMany("Findings")
                        .HasForeignKey("RootCauseId")
                        .HasConstraintName("FK__Finding__RootCau__7F2BE32F");

                    b.HasOne("ASM_Repositories.Entities.FindingSeverity", "SeverityNavigation")
                        .WithMany("Findings")
                        .HasForeignKey("Severity")
                        .HasConstraintName("FK__Finding__Severit__7E37BEF6");

                    b.HasOne("ASM_Repositories.Entities.FindingStatus", "StatusNavigation")
                        .WithMany("Findings")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK__Finding__Status__03F0984C");

                    b.Navigation("Audit");

                    b.Navigation("AuditItem");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Dept");

                    b.Navigation("Reviewer");

                    b.Navigation("RootCause");

                    b.Navigation("SeverityNavigation");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Notification", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.AttachmentEntityType", "EntityTypeNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("EntityType")
                        .HasConstraintName("FK__Notificat__Entit__208CD6FA");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__1F98B2C1");

                    b.Navigation("EntityTypeNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ReportRequest", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.UserAccount", "RequestedByNavigation")
                        .WithMany("ReportRequests")
                        .HasForeignKey("RequestedBy")
                        .HasConstraintName("FK__ReportReq__Reque__2B0A656D");

                    b.Navigation("RequestedByNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.UserAccount", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Department", "Dept")
                        .WithMany("UserAccounts")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK__UserAccou__DeptI__48CFD27E");

                    b.HasOne("ASM_Repositories.Entities.Role", "RoleNameNavigation")
                        .WithMany("UserAccounts")
                        .HasForeignKey("RoleName")
                        .IsRequired()
                        .HasConstraintName("FK__UserAccou__RoleN__47DBAE45");

                    b.Navigation("Dept");

                    b.Navigation("RoleNameNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ActionStatus", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AttachmentEntityType", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Audit", b =>
                {
                    b.Navigation("AuditApprovals");

                    b.Navigation("AuditChecklistItems");

                    b.Navigation("AuditCriteriaMaps");

                    b.Navigation("AuditDocuments");

                    b.Navigation("AuditScopeDepartments");

                    b.Navigation("AuditTeams");

                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditChecklistItem", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditCriterion", b =>
                {
                    b.Navigation("AuditCriteriaMaps");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditStatus", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Department", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("AuditScopeDepartments");

                    b.Navigation("DepartmentHeads");

                    b.Navigation("Findings");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Finding", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.FindingSeverity", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.FindingStatus", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Role", b =>
                {
                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.RootCause", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.UserAccount", b =>
                {
                    b.Navigation("ActionAssignedByNavigations");

                    b.Navigation("ActionAssignedToNavigations");

                    b.Navigation("Attachments");

                    b.Navigation("AuditApprovals");

                    b.Navigation("AuditDocuments");

                    b.Navigation("AuditLogs");

                    b.Navigation("AuditTeams");

                    b.Navigation("Audits");

                    b.Navigation("ChecklistTemplates");

                    b.Navigation("DepartmentHeads");

                    b.Navigation("FindingCreatedByNavigations");

                    b.Navigation("FindingReviewers");

                    b.Navigation("Notifications");

                    b.Navigation("ReportRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
