// <auto-generated />
using System;
using ASM_Repositories.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM_Repositories.Migrations
{
    [DbContext(typeof(AuditManagementSystemForAviationAcademyContext))]
    partial class AuditManagementSystemForAviationAcademyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASM_Repositories.Entities.Action", b =>
                {
                    b.Property<Guid>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ActionID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AssignedDeptId")
                        .HasColumnType("int")
                        .HasColumnName("AssignedDeptID");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FindingID");

                    b.Property<byte?>("ProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("ReviewFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ActionId")
                        .HasName("PK__Action__FFE3F4B969F73F89");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("AssignedDeptId");

                    b.HasIndex("FindingId");

                    b.HasIndex("Status");

                    b.HasIndex(new[] { "AssignedTo", "Status" }, "IX_Action_AssignedTo_Status");

                    b.HasIndex(new[] { "DueDate" }, "IX_Action_DueDate");

                    b.ToTable("Action", "ams", t =>
                        {
                            t.HasTrigger("trg_Log_Action");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ActionStatus", b =>
                {
                    b.Property<string>("ActionStatus1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ActionStatus");

                    b.HasKey("ActionStatus1")
                        .HasName("PK__ActionSt__7B3DC58E4712C633");

                    b.ToTable("ActionStatus", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Attachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AttachmentID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("ContentHash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("RetentionUntil")
                        .HasColumnType("date");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AttachmentId")
                        .HasName("PK__Attachme__442C64DEB00D1A32");

                    b.HasIndex("UploadedBy");

                    b.HasIndex(new[] { "EntityType", "EntityId" }, "IX_Attachment_Entity");

                    b.ToTable("Attachment", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AttachmentEntityType", b =>
                {
                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EntityType")
                        .HasName("PK__Attachme__F21D4CA20B367E90");

                    b.ToTable("AttachmentEntityType", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Audit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Scope")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TemplateID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditId")
                        .HasName("PK__Audit__A17F23B8A84C25B5");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Status");

                    b.HasIndex("TemplateId");

                    b.ToTable("Audit", "ams", t =>
                        {
                            t.HasTrigger("trg_Log_Audit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditChecklistItem", b =>
                {
                    b.Property<Guid>("AuditItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditItemID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("QuestionTextSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditItemId")
                        .HasName("PK__AuditChe__E37F18C24E61F8E1");

                    b.HasIndex(new[] { "AuditId" }, "IX_Audit_AuditID");

                    b.ToTable("AuditChecklistItem", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LogID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LogId")
                        .HasName("PK__AuditLog__5E5499A8DD92FB1C");

                    b.HasIndex("PerformedBy");

                    b.HasIndex(new[] { "EntityId" }, "IX_AuditLog_EntityID");

                    b.HasIndex(new[] { "PerformedAt" }, "IX_AuditLog_PerformedAt")
                        .IsDescending();

                    b.ToTable("AuditLog", "log");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditStatus", b =>
                {
                    b.Property<string>("AuditStatus1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AuditStatus");

                    b.HasKey("AuditStatus1")
                        .HasName("PK__AuditSta__45D7E6369D4F51B0");

                    b.ToTable("AuditStatus", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditTeam", b =>
                {
                    b.Property<Guid>("AuditTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditTeamID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID");

                    b.Property<bool>("IsLead")
                        .HasColumnType("bit");

                    b.Property<string>("RoleInTeam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("AuditTeamId")
                        .HasName("PK__AuditTea__7093F172898EA316");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AuditId" }, "IX_AuditTeam_AuditID");

                    b.HasIndex(new[] { "AuditId", "UserId" }, "UQ__AuditTea__7007AF731E5F25A8")
                        .IsUnique();

                    b.ToTable("AuditTeam", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ChecklistItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ItemID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AnswerType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeverityDefault")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TemplateID");

                    b.HasKey("ItemId")
                        .HasName("PK__Checklis__727E83EBAC8657E6");

                    b.HasIndex("SeverityDefault");

                    b.HasIndex(new[] { "TemplateId" }, "IX_Checklist_Template");

                    b.ToTable("ChecklistItem", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ChecklistTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TemplateID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TemplateId")
                        .HasName("PK__Checklis__F87ADD07BFF290DB");

                    b.HasIndex("CreatedBy");

                    b.ToTable("ChecklistTemplate", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DeptId")
                        .HasName("PK__Departme__0148818E12B2BECB");

                    b.ToTable("Department", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Finding", b =>
                {
                    b.Property<Guid>("FindingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FindingID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditID");

                    b.Property<Guid?>("AuditItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditItemID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalAuditorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReviewerID");

                    b.Property<int?>("RootCauseId")
                        .HasColumnType("int")
                        .HasColumnName("RootCauseID");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("FindingId")
                        .HasName("PK__Finding__19D671C22DCDC03A");

                    b.HasIndex("AuditItemId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("RootCauseId");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex(new[] { "AuditId", "Status" }, "IX_Finding_AuditID_Status");

                    b.HasIndex(new[] { "DeptId", "Severity" }, "IX_Finding_DeptID_Severity");

                    b.ToTable("Finding", "ams", t =>
                        {
                            t.HasTrigger("trg_Log_Finding");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ASM_Repositories.Entities.FindingSeverity", b =>
                {
                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Severity")
                        .HasName("PK__FindingS__96F5CD15C02AA915");

                    b.ToTable("FindingSeverity", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.FindingStatus", b =>
                {
                    b.Property<string>("FindingStatus1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FindingStatus");

                    b.HasKey("FindingStatus1")
                        .HasName("PK__FindingS__B9A531DF5E4F114E");

                    b.ToTable("FindingStatus", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NotificationID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E327A4D606D");

                    b.HasIndex("EntityType");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ReportRequest", b =>
                {
                    b.Property<Guid>("ReportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReportRequestID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("RequestedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportRequestId")
                        .HasName("PK__ReportRe__1609F931C68D52FD");

                    b.HasIndex("RequestedBy");

                    b.ToTable("ReportRequest", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Role", b =>
                {
                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("RoleName")
                        .HasName("PK__Role__8A2B616187FE0763");

                    b.ToTable("Role", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.RootCause", b =>
                {
                    b.Property<int>("RootCauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RootCauseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RootCauseId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RootCauseId")
                        .HasName("PK__RootCaus__EAE5E40E2FAE18E7");

                    b.ToTable("RootCause", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("UserId")
                        .HasName("PK__UserAcco__1788CCAC24440160");

                    b.HasIndex("RoleName");

                    b.HasIndex(new[] { "DeptId", "RoleName" }, "IX_User_Dept_Role");

                    b.HasIndex(new[] { "Email" }, "UQ__UserAcco__A9D105346D1562FC")
                        .IsUnique();

                    b.ToTable("UserAccount", "auth", t =>
                        {
                            t.HasTrigger("trg_UserAccount_Delete");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ASM_Repositories.Entities.VwFindingHistory", b =>
                {
                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("FindingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FindingID");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ToTable((string)null);

                    b.ToView("vw_FindingHistory", "ams");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Action", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.UserAccount", "AssignedByNavigation")
                        .WithMany("ActionAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .HasConstraintName("FK__Action__Assigned__7F2BE32F");

                    b.HasOne("ASM_Repositories.Entities.Department", "AssignedDept")
                        .WithMany("Actions")
                        .HasForeignKey("AssignedDeptId")
                        .HasConstraintName("FK__Action__Assigned__01142BA1");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "AssignedToNavigation")
                        .WithMany("ActionAssignedToNavigations")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK__Action__Assigned__00200768");

                    b.HasOne("ASM_Repositories.Entities.Finding", "Finding")
                        .WithMany("Actions")
                        .HasForeignKey("FindingId")
                        .IsRequired()
                        .HasConstraintName("FK__Action__FindingI__7E37BEF6");

                    b.HasOne("ASM_Repositories.Entities.ActionStatus", "StatusNavigation")
                        .WithMany("Actions")
                        .HasForeignKey("Status")
                        .HasConstraintName("FK__Action__Status__02084FDA");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("AssignedDept");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("Finding");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Attachment", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.AttachmentEntityType", "EntityTypeNavigation")
                        .WithMany("Attachments")
                        .HasForeignKey("EntityType")
                        .IsRequired()
                        .HasConstraintName("FK__Attachmen__Entit__07C12930");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "UploadedByNavigation")
                        .WithMany("Attachments")
                        .HasForeignKey("UploadedBy")
                        .HasConstraintName("FK__Attachmen__Uploa__08B54D69");

                    b.Navigation("EntityTypeNavigation");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Audit", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.UserAccount", "ApprovedByNavigation")
                        .WithMany("AuditApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__Audit__ApprovedB__5FB337D6");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "CreatedByNavigation")
                        .WithMany("AuditCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Audit__CreatedBy__5EBF139D");

                    b.HasOne("ASM_Repositories.Entities.AuditStatus", "StatusNavigation")
                        .WithMany("Audits")
                        .HasForeignKey("Status")
                        .HasConstraintName("FK__Audit__Status__5DCAEF64");

                    b.HasOne("ASM_Repositories.Entities.ChecklistTemplate", "Template")
                        .WithMany("Audits")
                        .HasForeignKey("TemplateId")
                        .HasConstraintName("FK__Audit__TemplateI__5CD6CB2B");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("StatusNavigation");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditChecklistItem", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Audit", "Audit")
                        .WithMany("AuditChecklistItems")
                        .HasForeignKey("AuditId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditChec__Audit__6C190EBB");

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditLog", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.UserAccount", "PerformedByNavigation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedBy")
                        .HasConstraintName("FK__AuditLog__Perfor__151B244E");

                    b.Navigation("PerformedByNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditTeam", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Audit", "Audit")
                        .WithMany("AuditTeams")
                        .HasForeignKey("AuditId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditTeam__Audit__66603565");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "User")
                        .WithMany("AuditTeams")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditTeam__UserI__6754599E");

                    b.Navigation("Audit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ChecklistItem", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.FindingSeverity", "SeverityDefaultNavigation")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("SeverityDefault")
                        .HasConstraintName("FK__Checklist__Sever__59063A47");

                    b.HasOne("ASM_Repositories.Entities.ChecklistTemplate", "Template")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("FK__Checklist__Templ__571DF1D5");

                    b.Navigation("SeverityDefaultNavigation");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ChecklistTemplate", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.UserAccount", "CreatedByNavigation")
                        .WithMany("ChecklistTemplates")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Checklist__Creat__5165187F");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Finding", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Audit", "Audit")
                        .WithMany("Findings")
                        .HasForeignKey("AuditId")
                        .IsRequired()
                        .HasConstraintName("FK__Finding__AuditID__71D1E811");

                    b.HasOne("ASM_Repositories.Entities.AuditChecklistItem", "AuditItem")
                        .WithMany("Findings")
                        .HasForeignKey("AuditItemId")
                        .HasConstraintName("FK__Finding__AuditIt__72C60C4A");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "CreatedByNavigation")
                        .WithMany("FindingCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Finding__Created__76969D2E");

                    b.HasOne("ASM_Repositories.Entities.Department", "Dept")
                        .WithMany("Findings")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK__Finding__DeptID__75A278F5");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "Reviewer")
                        .WithMany("FindingReviewers")
                        .HasForeignKey("ReviewerId")
                        .HasConstraintName("FK__Finding__Reviewe__7A672E12");

                    b.HasOne("ASM_Repositories.Entities.RootCause", "RootCause")
                        .WithMany("Findings")
                        .HasForeignKey("RootCauseId")
                        .HasConstraintName("FK__Finding__RootCau__74AE54BC");

                    b.HasOne("ASM_Repositories.Entities.FindingSeverity", "SeverityNavigation")
                        .WithMany("Findings")
                        .HasForeignKey("Severity")
                        .HasConstraintName("FK__Finding__Severit__73BA3083");

                    b.HasOne("ASM_Repositories.Entities.FindingStatus", "StatusNavigation")
                        .WithMany("Findings")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK__Finding__Status__797309D9");

                    b.Navigation("Audit");

                    b.Navigation("AuditItem");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Dept");

                    b.Navigation("Reviewer");

                    b.Navigation("RootCause");

                    b.Navigation("SeverityNavigation");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Notification", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.AttachmentEntityType", "EntityTypeNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("EntityType")
                        .HasConstraintName("FK__Notificat__Entit__0F624AF8");

                    b.HasOne("ASM_Repositories.Entities.UserAccount", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__0E6E26BF");

                    b.Navigation("EntityTypeNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ReportRequest", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.UserAccount", "RequestedByNavigation")
                        .WithMany("ReportRequests")
                        .HasForeignKey("RequestedBy")
                        .HasConstraintName("FK__ReportReq__Reque__19DFD96B");

                    b.Navigation("RequestedByNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.UserAccount", b =>
                {
                    b.HasOne("ASM_Repositories.Entities.Department", "Dept")
                        .WithMany("UserAccounts")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK__UserAccou__DeptI__48CFD27E");

                    b.HasOne("ASM_Repositories.Entities.Role", "RoleNameNavigation")
                        .WithMany("UserAccounts")
                        .HasForeignKey("RoleName")
                        .IsRequired()
                        .HasConstraintName("FK__UserAccou__RoleN__47DBAE45");

                    b.Navigation("Dept");

                    b.Navigation("RoleNameNavigation");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ActionStatus", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AttachmentEntityType", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Audit", b =>
                {
                    b.Navigation("AuditChecklistItems");

                    b.Navigation("AuditTeams");

                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditChecklistItem", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.AuditStatus", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Department", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Findings");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Finding", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.FindingSeverity", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.FindingStatus", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.Role", b =>
                {
                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.RootCause", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ASM_Repositories.Entities.UserAccount", b =>
                {
                    b.Navigation("ActionAssignedByNavigations");

                    b.Navigation("ActionAssignedToNavigations");

                    b.Navigation("Attachments");

                    b.Navigation("AuditApprovedByNavigations");

                    b.Navigation("AuditCreatedByNavigations");

                    b.Navigation("AuditLogs");

                    b.Navigation("AuditTeams");

                    b.Navigation("ChecklistTemplates");

                    b.Navigation("FindingCreatedByNavigations");

                    b.Navigation("FindingReviewers");

                    b.Navigation("Notifications");

                    b.Navigation("ReportRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
